### ISSUE TITLE
"ERROR TypeError: Cannot read property 'nativeElement' of undefined" on Angular 9

### ISSUE THREAD

**Issue by oscarortiz14** [werthdavid/ngx-kjua#10]
After updating to Angular 9, the following error occurs:

`ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at NgxKjuaComponent.updateView (ngx-kjua-example-7-ybjnas.stackblitz.io/turbo_modules/ngx-kjua@1.6.0/bundles/ngx-kjua.umd.js:159)`

Forked stackblitz project: https://stackblitz.com/edit/ngx-kjua-example-7-ybjnas

**Comment by josineiaraujo** [comment]
I also have this same problem
![dsd](https://user-images.githubusercontent.com/19354481/74403225-4bb24a00-4e05-11ea-8dc3-cf1614494b35.png)

**Comment by josineiaraujo** [comment]
#11  I found a solution that worked for me and made a pull request

**Comment by werthdavid** [comment]
I'm sorry but #11 is just a workaround in my opinion. Thank you very much for the work but I think I found a more correct solution that will be released with 1.6.1

**Comment by werthdavid** [comment]
I forked the above example and updated to ngx-kjua@1.6.1, seems to be fine now, please confirm
https://stackblitz.com/edit/ngx-kjua-example-7-x5gxwe?file=package.json

**Comment by oscarortiz14** [comment]
Nice, it works like a charm!
