### ISSUE TITLE
Error during compilation in Angular v9: Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null

### ISSUE THREAD

**Issue by josineiaraujo** [werthdavid/ngx-kjua#13]
The error occurs: (_Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null_) during compilation in Angular v9; **The error occurs because kjua-svg uses svg.js@2.7.1; Update this, please !!!**  
[https://github.com/werthdavid/kjua/issues/2#issue-578281722]

**Comment by werthdavid** [comment]
svg.js@2.7.1 is the latest version. 
BTW: feel free to make a PR if you know how to fix that

**Comment by werthdavid** [comment]
The latest version does btw run with Angular 9 and I cannot reproduce your issue. can you provide more information?

**Comment by josineiaraujo** [comment]
_**svg@3.0 is a newer version!**_
I identified that **svg@2.7.1** is causing this problem for min, in addition several other programmers are having the same problem using packages that depend on **svg@2.7.1**, as is the case with apexcharts that has already updated to the latest version recent, **svg@3.0**
