### ISSUE TITLE
An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by sergiogoncalves** [werthdavid/ngx-kjua#19]
Angular 7
Using primeng

I'm facing the folowing error:

ERROR in node_modules/ngx-kjua/app/modules/ngx-kjua/ngx-kjua.component.d.ts(82,9): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by werthdavid** [comment]
Please try with the lastest version 1.8.0

**Comment by jarios71** [comment]
Try **"skipLibCheck": true** inside **compilerOptions** in tsconfig.json
