### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by takahser** [werthdavid/ngx-kjua#2]
When using `ngx-kjua` with Angular Universal (for SSR support), an error is thrown, when starting the node web server:

**ReferenceError: window is not defined**

**Comment by werthdavid** [comment]
I don't have any experience with Angular Universal sorry... I just found this, maybe it helps?
https://github.com/angular/universal/issues/830#issuecomment-345228799

**Comment by takahser** [comment]
I opened a PR to fix this: https://github.com/werthdavid/ngx-kjua/pull/3

**Comment by werthdavid** [comment]
Published 1.2.0, thanks for the PR 😄

**Comment by takahser** [comment]
@werthdavid @jcudzich While I'm sure that some browser objects like `window`, `document`, etc. only exist in  browser implementations of JS, I'm not sure if we should go as far as restricting kjua from getting loaded on any platform, other than the browser one. For example, NativeScript uses the [platformBrowserDynamic](https://angular.io/api/platform-browser-dynamic/platformBrowserDynamic) and I'm not sure, what `isPlatformBrowser` would return in this case. What's more, regarding `isPlatformWorkerApp`, `isPlatformWorkerUi`, I'm not sure if they run on the browser as well?
Just thinking out loud here.

Regarding Renderer2, does this relate to this PR as well?

**Comment by werthdavid** [comment]
You're right. Since everything works fine now I'll leave it as it is. Just thought we could optimize a little bit 😉

**Comment by jcudzich** [comment]
@takahser Good observation about other platforms than the browser, I think you're right in this case.
Btw Renderer2 is just good habits in this case.

**Comment by takahser** [comment]
@jcudzich Since I'm not sure what you mean, could you elaborate on the Renderer2 thing? Because I'm not familiar with it. Also, is it related to this PR?

**Comment by jcudzich** [comment]
Rerender2 is related to manipulate DOM on the other platforms than browser.
Of course this code works in browser:
```
this.div.nativeElement.style.width = +this.size;
```
but Rerender2 class imported from `@angular/core` is more safe:
```
constructor(private rerender2: Rerender2) {}

updateView(): void {
  this.rerender2.setStyle(this.div.nativeElement, 'width', +this.size);
}
```
It's abstraction for manipulate DOM in platforms that doesn't have access to DOM.
I think is related because ServerPlatform is one these platforms.

I didn't point out any problem, just suggested refactoring :)

**Comment by takahser** [comment]
@jcudzich Ah nice, I didn't know, but this is cool. Thanks for your explanation. 👍🏼

Anyways, in this case, the incompatible code comes from the kjua (not ngx-kjua) library, which is just imported and used as-is. More specifically, the kjua lib is leveraging some browser-only objects, such as `windows` and `document`, which caused the problem on the server platform. Since kjua is a vanilla JS lib and also just a dependency (not ngx-kjua code), I assume it's unfortunately not possible to use rerenderer2. ☹️
