### ISSUE TITLE
Cannot read property 'getAttribute' of undefined - on Ionic 5

### ISSUE THREAD

**Issue by m0w4hhed** [werthdavid/ngx-kjua#21]
How to use this library on Ionic 5? i've got an error while use this library

Step to reproduce:
1. in blabla.module.ts =
`
import { NgxKjuaModule } from 'ngx-kjua'; 
...
imports: [
   ...
   NgxKjuaModule,
]
`
2. in blabla.page.html =
`
<ngx-kjua [text]="'testttttt'"></ngx-kjua>
`

i use ngx-kjua@1.12.0

**Comment by marcfpereira** [comment]
Hi! I'm getting the same error in Angular. I have done the same as you but it has not worked for me. I had to delete this version and go back to an older one that worked for me.

**Comment by davemecha** [comment]
I can confirm as a workaround that this problem exists with ngx-kjua@1.12.0. Rolling back one version to ngx-kjua@1.8.0 is a feasible workaround.

**Comment by boan-anbo** [comment]
submitted a fix here: https://github.com/werthdavid/kjua/pull/5 

for workaround: change the default value of `[image]` from `"undefined"` to `''`

**Comment by werthdavid** [comment]
sorry for the inconvenience, please try the latest version (ngx-kjua@1.12.1)
