### ISSUE TITLE
CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by steinbachio** [werthdavid/ngx-kjua#23]
Hi,

after upgrading to Angular 10 I am getting this warning on build.

Warning: /Users/m/Projects/stocki.fy/ng-client/src/app/app.module.ts depends on 'ngx-kjua'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

I am importing and using the module like shown in the readme.

**Comment by werthdavid** [comment]
Please try with ngx-kjua@1.12.2 I hope it's fixed now
