### ISSUE TITLE
How can add pasword in QR code

### ISSUE THREAD

**Issue by soultrue** [werthdavid/ngx-kjua#24]
Hi,

I would like to add password in my QR code so if and when I scan my barcode, it will ask for password and if I entered correct password then only will able to read the content of barcode.

Is it possible in your QR code script?

**Comment by werthdavid** [comment]
Hey, sorry that is not possible. It also depends on how you read the qr-code.

**Comment by soultrue** [comment]
Thanks @werthdavid
