### ISSUE TITLE
console

### ISSUE THREAD

**Issue by Darkmarus** [werthdavid/ngx-kjua#25]
![image](https://user-images.githubusercontent.com/13181325/109042259-bea7ff00-76ae-11eb-92fa-e9b7ecc3f032.png)

**Comment by werthdavid** [comment]
![ngxkjua](https://user-images.githubusercontent.com/4696067/109115417-55240100-773f-11eb-81a0-c0d124275738.png)

**Comment by werthdavid** [comment]
(you have to install 1.12.3)
