### ISSUE TITLE
Feature request: Qr code with image

### ISSUE THREAD

**Issue by pandiyaavps** [werthdavid/ngx-kjua#29]
@werthdavid How to apply image margin, with background hide
![filename (34)](https://user-images.githubusercontent.com/31888700/115495674-d0a8b700-a285-11eb-8bf0-0643efb3eb4c.png)

**Comment by werthdavid** [comment]
you mean a "white border" between the logo and the QR code? sorry, the library can't handle that, you have to provide a logo with some white space around it.

**Comment by pandiyaavps** [comment]
@werthdavid But even with logo with border image QR code logo overlapping.

Our QR code
![NgxKjua](https://user-images.githubusercontent.com/31888700/115506680-c512bb80-a298-11eb-9f3b-d36a0486e71e.png)

Other QR Code with image margin center
![filename (32)](https://user-images.githubusercontent.com/31888700/115506098-19696b80-a298-11eb-88a5-098d228deae1.png)

**Comment by rbalet** [comment]
@werthdavid would this feature-request be implemented in the future ?

**Comment by werthdavid** [comment]
Sorry, kjua internally uses "qrcode-generator" which does not support that
