### ISSUE TITLE
feature request : add element id

### ISSUE THREAD

**Issue by rbalet** [werthdavid/ngx-kjua#39]
## Description
Being able to add an id to the image could be really useful. 

## Objective
Being able to get the element with its ID so we could download the image in the local machine.

## Implementation
@Input() id: string

## Result
```html
<svg id="myId" xmlns="http://www.w3.org/2000/svg" width="200" height="200" viewBox="0 0 200 200" style="width: 200px; height: 200px;">
```

**Comment by werthdavid** [comment]
That  should be no problem

**Comment by werthdavid** [comment]
Please try 1.13.0

**Comment by rbalet** [comment]
@werthdavid Perfectly working, closing the issue. Thanks!
