### ISSUE TITLE
QR Code Image Style

### ISSUE THREAD

**Issue by m-khnarges** [werthdavid/ngx-kjua#4]
Hello

Thanks for your professional package for generating QR code.
I'm using this image in a portlet and I like to have some options to style the QR code image e.g. I need variable size for being responsive or some CSS styles to place image in the middle of the portlet. I used ::ng-deep img {} in angular component styles to add style to below image tag, but it affects all image tags in all components we have.
I think it will be good if you add style options to ngx-kjua or at least add spcific class to below image tag for flexible usage of ng-deep to add style to that.
```
<ngx-kjua>
    <div>
        <img src="" width="400" height="400" style="width: 200px; height: 200px;">
    </div>
</ngx-kjua>
```
Thanks

**Comment by werthdavid** [comment]
Hey there.
so you would like to have an parameter like "cssClass" that is added to the container so you can style it from outside?
I played around with that a little bit and there are two problems...
1. ngx-kjua renders a div-container and inside there is either the img-element or a canvas (depending on what you set). What I can do is adding the cssClass to that div.
2. specifically width and height are not changeable with the current implementation of kjua (not ngx-kjua!). in the canvasToImg method of kjua, the img-tag gets those parameters set directly to the element 
``` 
<img width="600" height="600" ...
```

and not

```
<img style="width: 600px; height: 600px" ...
```

so if you want to apply width and height transformations to the css class it will be ignored.

What should we do? Do you want the cssClass parameter anyway? I don't know if the owner of kjua will accept a PR that would change that behavior...

**Comment by m-khnarges** [comment]
Yes, I would like to have something like CSS class parameter or just a class name to use instead of img tag in the code below.
Now I style QR image with this code:
```
::ng-deep img:not(.img-circle) { margin-left: auto; margin-right: auto; display: block; max-width: 100%; height: auto !important; }
```
The above code makes all images to be in the middle of their outer division with max width 100%, but I just want QR image to have that style.

Thanks.

**Comment by m-khnarges** [comment]
Thanks for your response, but I got the error below when I run npm install with both 1.2.0 and 1.3.0 versions
```
ERROR in ./node_modules/ngx-kjua/esm2015/ngx-kjua.js
Module not found: Error: Can't resolve 'kjua' in '/Users/narges/Documents/git/bitbucket/ewal-main/public/ang/node_modules/ngx-kjua/esm2015'
```

**Comment by m-khnarges** [comment]
It worked for me
Thanks a lot!

**Comment by mohamedshalghm** [comment]
Contact QR Code Type , For iPhone Camera QR Code Reader while using uf words if words count more than three not readed else read if you please help
