### ISSUE TITLE
feature request : output the newly created element

### ISSUE THREAD

**Issue by rbalet** [werthdavid/ngx-kjua#40]
## Description
I would find it useful that the component does emit his value when it did finish initializing it.

## Objective
Being able to bind it with a button that let the user download the file.

## Implementation
`@Output() emitData = new EventEmitter<any>()`

## Result
```html
<ngx-kjua
 (emoitData)="downloadFIle = $event"
></ngx-kjua>
```

**Comment by werthdavid** [comment]
Please try 1.13.0

**Comment by rbalet** [comment]
@werthdavid Working like a charm -> `(codeFinished)`. Thx a lot!

**Comment by luquettacwb** [comment]
I've try to use:

<ngx-kjua
...
[elementId]="1234"
></ngx-kjua>

But with this error:

Template parse errors:
Can't bind to 'elementId' since it isn't a known property of 'ngx-kjua'.

Is it possible to download the QRCode?

**Comment by werthdavid** [comment]
@luquettacwb what exactly would you need? a BLOB?

**Comment by luquettacwb** [comment]
> @luquettacwb what exactly would you need? a BLOB?

Yes, if possible

**Comment by werthdavid** [comment]
Hmm does the output (codeFinished) help? did you try that?
