### ISSUE TITLE
Update to Angular 13

### ISSUE THREAD

**Issue by scomans** [werthdavid/ngx-kjua#49]
I pretty sure you are already aware but this lib needs an update 😉

**Comment by werthdavid** [comment]
That's right! 😉  I'll see if I can find time this weekend..

**Comment by scomans** [comment]
Perfect! Thank you very much!

**Comment by werthdavid** [comment]
Can you test with v1.14.0 please

**Comment by scomans** [comment]
Seems to work fine. Thanks
