### ISSUE TITLE
 error NG8001: 'ngx-kjua' is not a known element:

### ISSUE THREAD

**Issue by playground** [werthdavid/ngx-kjua#53]
Trying out v2.0 but getting error with Angular v13.0.0

Error: src/app/components/qr-code/qr-code.component.html:4:7 - error NG8001: 'ngx-kjua' is not a known element:
1. If 'ngx-kjua' is an Angular component, then verify that it is part of this module.
2. If 'ngx-kjua' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

  4       <ngx-kjua
          ~~~~~~~~~
  5       [renderAsync]="true"
    ~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 13       [size]="size"
    ~~~~~~~~~~~~~~~~~~~
 14       ></ngx-kjua>

**Comment by werthdavid** [comment]
Can you please test with 2.0.1

**Comment by rbalet** [comment]
@Gamaroff Should be fixed
@werthdavid  I think you shall close this issue

**Comment by playground** [comment]
Thank you, will give it a try.

**Comment by rbalet** [comment]
@werthdavid Hi there. I assume you can close this issue.

Cheers
