### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by xraybrain** [werthdavid/ngx-kjua#57]
was using this in angular 13 universal and this error occurred.

Setup:

`<ngx-kjua [text]="settings.data" [renderAsync]="false" [render]="'svg'" [crisp]="true"
                                [minVersion]="1" [ecLevel]="settings.errorCorrectionLevel" [size]="400"
                                [ratio]="undefined" [fill]="settings.fgColor" [back]="settings.bgColor" [rounded]="100"
                                [quiet]="1" [mode]="'plain'" [mSize]="30" [mPosX]="50" [mPosY]="50"
                                [label]="'label text'" [fontname]="'sans-serif'" [fontcolor]="'#ff9818'"
                                [image]="undefined" [cssClass]="'image-auto'"></ngx-kjua>`

**Comment by werthdavid** [comment]
What version exactly?

**Comment by rbalet** [comment]
@werthdavid Hi there. I assume you can close this issue.

Cheers
