### ISSUE TITLE
ERROR in ./src/app/modules/ngx-kjua/ngx-kjua.component.ts

### ISSUE THREAD

**Issue by sebasmdl** [werthdavid/ngx-kjua#6]
ERROR in ./src/app/modules/ngx-kjua/ngx-kjua.component.ts
Module not found: Error: Can't resolve 'kjua' in '/Users/dev/Documents/GitHub/ngx-kjua/src/app/modules/ngx-kjua'
Failed to compile

- npm install kjua - ok

**Comment by werthdavid** [comment]
should be fixed with 1.3.1
