### ISSUE TITLE
Use the package in Angular 16

### ISSUE THREAD

**Issue by Sergiobop** [werthdavid/ngx-kjua#74]
Hi, first of all, thanks for this awesome package.

I'm having trouble installing the lib in an Angular 16 app:
peer @angular/core@">=14.0.0 <16.0.0" from ngx-kjua@2.0.4

Thanks

**Comment by werthdavid** [comment]
That's right! Please test 2.1.0

**Comment by Sergiobop** [comment]
Amazing!
