### ISSUE TITLE
update - changelog : v2.1.0

### ISSUE THREAD

**Issue by rbalet** [werthdavid/ngx-kjua#76]
Add the v2.1.0 to the changelog.

@werthdavid Thx for the update <3.

If you wish I can do such update on my own if you give me the access :)

## Feature-request
I'm starting to do as follow we my libraries, but basically I update the library version accordingly to the angular one.  
Meaning the version here would be v16.0.0.

Doing that way let people see better & directly which version to install.

What do you think ?

**Comment by werthdavid** [comment]
I think this is a great idea!

**Comment by werthdavid** [comment]
Done
