### ISSUE TITLE
bug: container height

### ISSUE THREAD

**Issue by rbalet** [werthdavid/ngx-kjua#79]
## Description
The container height isn't the same as the svg one

![image](https://github.com/werthdavid/ngx-kjua/assets/44493964/c3f0c902-fa2c-48be-98d1-65113b8a7b51)

## Idea how to fix
I'd give the div that we have around the svg the same height & width

## Why is it a problem.
As you can see in the picture, I would have loved to add a rounded border all around, but this isn't working properly.

**Comment by rbalet** [comment]
Closing as completed https://github.com/werthdavid/ngx-kjua/pull/80

**Comment by rbalet** [comment]
@werthdavid Could you push a new version over on npm?

**Comment by werthdavid** [comment]
As soon as CI is fixed! On it

**Comment by rbalet** [comment]
@werthdavid I've looked at the error from the Ci.

You may try to revert the dependencies update to the following. 
_In my experience, updating karma may create errors_. 

```typescript
 "devDependencies": {
    "@angular-devkit/build-angular": "^16.2.0",
    "@angular/cli": "^16.2.0",
    "@types/jasmine": "~4.3.0",
    "@types/node": "^18.7.16",
    "core-js": "^3.25.1",
    "jasmine-core": "~4.4.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.1",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "ng-packagr": "^16.2.0",
    "rxjs": "~7.8.1",
    "ts-node": "~10.5.0",
    "tslint": "~6.1.3",
    "typescript": "~5.1.6"
  }
```

**Comment by werthdavid** [comment]
Should be available

**Comment by rbalet** [comment]
@werthdavid Thx, I tried and it worked like a charm.

Thx a lot for your reactivity
