### ISSUE TITLE
Angular 6.0.2 cannot find module 'ngx-kjua' Vers. 1.4.0

### ISSUE THREAD

**Issue by de-mim-1974** [werthdavid/ngx-kjua#8]
Angular: 6.0.2
ngx-kjua: 1.4.0

Imported into the root level app.module.ts using ReadMe details.
`import { NgxKjuaModule } from 'ngx-kjua';`

`ng serve` throws the following error. VS-Code highlights and shows the same:

`ERROR in src/app/app.module.ts(18,31): error TS2307: Cannot find module 'ngx-kjua'.`

All dependencies are installed and visible in the node modules directory

PS: With ngx-kjua@1.3.2 it works!

**Comment by dotob** [comment]
same here with angular 7.2.15

**Comment by digoburigo** [comment]
Any news on this issue? Its still happening in Angular 8.1.0

**Comment by werthdavid** [comment]
Sorry guys, didn't get any notification about that issue... I'll look into it!

**Comment by werthdavid** [comment]
I tested it with 1.4.1 and a fresh CLI installation (7.3.8) and it works fine. Can you verify it?

**Comment by werthdavid** [comment]
Please re-open it if the problem still occurs
