### ISSUE TITLE
Error after upgrading to 18

### ISSUE THREAD

**Issue by Sergiobop** [werthdavid/ngx-kjua#98]
Hi! First of all, thanks for this awesome package.

I'm having some issues after upgrading to Angular 18 and 18.1.1 version of this lib:
```
 [ERROR] Cannot assign to import "stringToBytes"

    node_modules/ngx-kjua/fesm2022/ngx-kjua.mjs:587:7:
      587 │ qr_gen.stringToBytes = qr_gen.stringToBytesFuncs["UTF-8"];
          ╵        ~~~~~~~~~~~~~

  Imports are immutable in JavaScript. To modify the value of this import, you must export a setter
  function in the imported file (e.g. "setStringToBytes") and then import and call that function
  here instead.
  ```
 
 I didn't have any issue in NG17
 Thanks
 
 Edit: I think this is the problem?
 https://github.com/werthdavid/ngx-kjua/blob/3ad7fa00e2fd0dd5dee354f9bec26acb002cc148/projects/ngx-kjua/src/lib/kjua/lib/qrcode.ts#L4
 
 I'm using the [application builder](https://angular.dev/tools/cli/build-system-migration) since it's recommended in v17 and higher

**Comment by rbalet** [comment]
@Sergiobop Can you try this pull request ? 

https://github.com/werthdavid/ngx-kjua/pull/99

**Comment by Sergiobop** [comment]
How can i test it @rbalet ?

Can we do a mini-release @werthdavid ? If so, i will test it ASAP

**Comment by rbalet** [comment]
@Sergiobop I woud
Either @werthdavid Push a temporary version, or

1. Download the library
2. `npm i` 
3. `ng build ngx-kjua --configuration production`
4.  `cd /dist/ngx-kjua`
5. `npm link`

That way you prepare locally the library

Then, in the project where you're using it, you use the local npm repo by doing : 
6. `npm link ngx-kjua`
7. Test it out

**Comment by werthdavid** [comment]
Feel free to test, didn't have much time this week sorry. I will probably find time today or tomorrow. If the suggested PR works, we can make a release.

**Comment by Sergiobop** [comment]
The compilation error is gone, but i get this now:
```
main.ts:5 ERROR TypeError: Cannot read properties of null (reading 'firstCreatePass')
    at createViewQuery (core.mjs:17743:15)
    at ɵɵviewQuery (core.mjs:27273:5)
    at NgxKjuaComponent_Query (ngx-kjua.component.ts:30:30)
    at executeViewQueryFn (core.mjs:12499:9)
    at renderView (core.mjs:12665:13)
    at renderComponent (core.mjs:12617:5)
    at renderChildComponents (core.mjs:12719:9)
    at renderView (core.mjs:12699:13)
    at renderComponent (core.mjs:12617:5)
    at renderChildComponents (core.mjs:12719:9)
   ```
   
   I don't know if its because i did something wrong in the process
   
   

>    Note: Is kjua-svg needed to work? In my old project i just did npm i ngx-kjua --save, not npm i ngx-kjua kjua-svg --save like the README says

**Comment by rbalet** [comment]
@Sergiobop Ah, forgot to tell you, but by using `link`, you need to add `"preserveSymlinks": true,` in your `angular.json` file

![image](https://github.com/werthdavid/ngx-kjua/assets/44493964/547a5d75-5cd6-4fa5-ac14-5e6406f4720d)

**Comment by Sergiobop** [comment]
Now:
```
✘ [ERROR] Could not resolve "qrcode-generator"

    node_modules/ngx-kjua/fesm2022/ngx-kjua.mjs:3:19:
      3 │ import qrcode from 'qrcode-generator';
        ╵                    ~~~~~~~~~~~~~~~~~~

  You can mark the path "qrcode-generator" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.
  ```

**Comment by rbalet** [comment]
@Sergiobop you're missing a dependency here, please do npm i qrcode-generator

**Comment by Sergiobop** [comment]
Okey, ITS WORKING @rbalet @werthdavid 

Should the README be updated to have that qrcode-generator dependency when installing the package? 
Personally i think the best would be just "npm i ngx-kjua" and works

**Comment by werthdavid** [comment]
thank you guy. I will update the readme accordingly

**Comment by rbalet** [comment]
@werthdavid @Sergiobop no, the qrcode-generator is a peerDependency, therefore it will be downloaded automatically while doing npm i ngx-kjua.

It is just not working while trying it locally.

Cheers

**Comment by Sergiobop** [comment]
> @werthdavid @Sergiobop no, the qrcode-generator is a peerDependency, therefore it will be downloaded automatically while doing npm i ngx-kjua.
> 
> It is just not working while trying it locally.
> 
> Cheers

Ohh, ok, thanks!

**Comment by werthdavid** [comment]
kjua-svg is NOT needed anymore!
Can be tested with the official 18.1.2 now!

**Comment by Sergiobop** [comment]
I will test it in a few minutes and close the issue if everything is good

Thanks a lot

**Comment by Sergiobop** [comment]
Everything is working fine,
Thanks again
